services:

  ### Trino query engine ###
  trino:
    image: trinodb/trino:467
    environment:
      - CATALOG_MANAGEMENT=dynamic
    volumes:
      - ./init-catalog-trino.sql:/home/trino/init-catalog-trino.sql
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8080/v1/status" ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s
    ports:
      - "9999:8080"
