{
 "title": "risingwave_dashboard",
 "description": "RisingWave Dashboard",
 "tags": [ "risingwave" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(process_cpu_seconds_total, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(process_cpu_seconds_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Actor/Table Id Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actor Info",
     "type": "table",
     "description": "Information about actors",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "group(actor_info{job=~\"$job\",instance=~\"$node\"}) by (actor_id, fragment_id, compute_node)",
       "query": "group(actor_info{job=~\"$job\",instance=~\"$node\"}) by (actor_id, fragment_id, compute_node)"
      }
     ]
    },
    {
     "title": "State Table Info",
     "type": "table",
     "description": "Information about state tables. Column `materialized_view_id` is the id of the materialized view that this state table belongs to.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name, table_type, materialized_view_id, fragment_id, compaction_group_id)",
       "query": "group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name, table_type, materialized_view_id, fragment_id, compaction_group_id)"
      }
     ]
    },
    {
     "title": "Actor Count (Group By Compute Node)",
     "type": "table",
     "description": "Actor count per compute node",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "targets": [
      {
       "expr": "count(actor_info{job=~\"$job\",instance=~\"$node\"}) by (compute_node)",
       "query": "count(actor_info{job=~\"$job\",instance=~\"$node\"}) by (compute_node)"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Source Throughput(rows/s)",
   "type": "timeseries",
   "description": "The figure shows the number of rows read by each source per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_source_output_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)",
     "legendFormat": "{{source_id}} {{source_name}} (fragment {{fragment_id}})",
     "query": "sum(rate(stream_source_output_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)"
    }
   ]
  },
  {
   "title": "Source Throughput(MB/s)",
   "type": "timeseries",
   "description": "The figure shows the number of bytes read by each source per second.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "expr": "(sum by (source_id, source_name, fragment_id)(rate(source_partition_input_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])))/(1000*1000)",
     "legendFormat": "{{source_id}} {{source_name}} (fragment {{fragment_id}})",
     "query": "(sum by (source_id, source_name, fragment_id)(rate(source_partition_input_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])))/(1000*1000)"
    }
   ]
  },
  {
   "title": "Sink Throughput(rows/s)",
   "type": "timeseries",
   "description": "The number of rows streamed into each sink per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_sink_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (sink_id) * on(sink_id) group_left(sink_name) group(sink_info{job=~\"$job\",instance=~\"$node\"}) by (sink_id, sink_name)",
     "legendFormat": "sink {{sink_id}} {{sink_name}}",
     "query": "sum(rate(stream_sink_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (sink_id) * on(sink_id) group_left(sink_name) group(sink_info{job=~\"$job\",instance=~\"$node\"}) by (sink_id, sink_name)"
    }
   ]
  },
  {
   "title": "Materialized View Throughput(rows/s)",
   "type": "timeseries",
   "description": "The figure shows the number of rows written into each materialized view per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "sum(rate(stream_mview_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id) * on(table_id) group_left(table_name) group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name)",
     "legendFormat": "mview {{table_id}} {{table_name}}",
     "query": "sum(rate(stream_mview_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id) * on(table_id) group_left(table_name) group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name)"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "description": "The time that the data between two consecutive barriers gets fully processed, i.e. the computation results are made durable into materialized views or sink to external systems. This metric shows to users the freshness of materialized views.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, database_id))",
     "legendFormat": "barrier_latency_p50 (database {{database_id}})",
     "query": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, database_id))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, database_id))",
     "legendFormat": "barrier_latency_p99 (database {{database_id}})",
     "query": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, database_id))"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum{job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) / rate(meta_barrier_duration_seconds_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "barrier_latency_avg (database {{database_id}})",
     "query": "rate(meta_barrier_duration_seconds_sum{job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) / rate(meta_barrier_duration_seconds_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) > 0"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "description": "Alerts in the system group by type:\n            - Too Many Barriers: there are too many uncommitted barriers generated. This means the streaming graph is stuck or under heavy load. Check 'Barrier Latency' panel.\n            - Recovery Triggered: cluster recovery is triggered. Check 'Errors by Type' / 'Node Count' panels.\n            - Lagging Version: the checkpointed or pinned version id is lagging behind the current version id. Check 'Hummock Manager' section in dev dashboard.\n            - Lagging Compaction: there are too many ssts in L0. This can be caused by compactor failure or lag of compactor resource. Check 'Compaction' section in dev dashboard, and take care of the type of 'Commit Flush Bytes' and 'Compaction Throughput', whether the throughput is too low.\n            - Lagging Vacuum: there are too many stale files waiting to be cleaned. This can be caused by compactor failure or lag of compactor resource. Check 'Compaction' section in dev dashboard.\n            - Abnormal Meta Cache Memory: the meta cache memory usage is too large, exceeding the expected 10 percent.\n            - Abnormal Block Cache Memory: the block cache memory usage is too large, exceeding the expected 10 percent.\n            - Abnormal Uploading Memory Usage: uploading memory is more than 70 percent of the expected, and is about to spill.\n            - Write Stall: Compaction cannot keep up. Stall foreground write, Check 'Compaction' section in dev dashboard.\n            - Abnormal Version Size: the size of the version is too large, exceeding the expected 300MB. Check 'Hummock Manager' section in dev dashboard.\n            - Abnormal Delta Log Number: the number of delta logs is too large, exceeding the expected 5000. Check 'Hummock Manager' and `Compaction` section in dev dashboard and take care of the type of 'Compaction Success Count', whether the number of trivial-move tasks spiking.\n            - Abnormal Pending Event Number: the number of pending events is too large, exceeding the expected 10000000. Check 'Hummock Write' section in dev dashboard and take care of the 'Event handle latency', whether the time consumed exceeds the barrier latency.\n            - Abnormal Object Storage Failure: the number of object storage failures is too large, exceeding the expected 50. Check 'Object Storage' section in dev dashboard and take care of the 'Object Storage Failure Rate', whether the rate is too high.\n            ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "all_barrier_nums{job=~\"$job\",instance=~\"$node\"} >= bool 200",
     "legendFormat": "Too Many Barriers {{database_id}}",
     "query": "all_barrier_nums{job=~\"$job\",instance=~\"$node\"} >= bool 200"
    },
    {
     "expr": "sum(rate(recovery_latency_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) > bool 0 + sum(recovery_failure_cnt{job=~\"$job\",instance=~\"$node\"}) > bool 0",
     "legendFormat": "Recovery Triggered {{recovery_type}}",
     "query": "sum(rate(recovery_latency_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) > bool 0 + sum(recovery_failure_cnt{job=~\"$job\",instance=~\"$node\"}) > bool 0"
    },
    {
     "expr": "((storage_current_version_id{job=~\"$job\",instance=~\"$node\"} - storage_checkpoint_version_id{job=~\"$job\",instance=~\"$node\"}) >= bool 100) + ((storage_current_version_id{job=~\"$job\",instance=~\"$node\"} - storage_min_pinned_version_id{job=~\"$job\",instance=~\"$node\"}) >= bool 100)",
     "legendFormat": "Lagging Version",
     "query": "((storage_current_version_id{job=~\"$job\",instance=~\"$node\"} - storage_checkpoint_version_id{job=~\"$job\",instance=~\"$node\"}) >= bool 100) + ((storage_current_version_id{job=~\"$job\",instance=~\"$node\"} - storage_min_pinned_version_id{job=~\"$job\",instance=~\"$node\"}) >= bool 100)"
    },
    {
     "expr": "sum(label_replace(storage_level_total_file_size{job=~\"$job\",instance=~\"$node\"}, 'L0', 'L0', 'level_index', '.*_L0') unless storage_level_total_file_size{job=~\"$job\",instance=~\"$node\"}) by (L0) >= bool 52428800",
     "legendFormat": "Lagging Compaction",
     "query": "sum(label_replace(storage_level_total_file_size{job=~\"$job\",instance=~\"$node\"}, 'L0', 'L0', 'level_index', '.*_L0') unless storage_level_total_file_size{job=~\"$job\",instance=~\"$node\"}) by (L0) >= bool 52428800"
    },
    {
     "expr": "storage_stale_object_count{job=~\"$job\",instance=~\"$node\"} >= bool 200",
     "legendFormat": "Lagging Vacuum",
     "query": "storage_stale_object_count{job=~\"$job\",instance=~\"$node\"} >= bool 200"
    },
    {
     "expr": "state_store_meta_cache_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 1.1",
     "legendFormat": "Abnormal Meta Cache Memory",
     "query": "state_store_meta_cache_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 1.1"
    },
    {
     "expr": "state_store_block_cache_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 1.1",
     "legendFormat": "Abnormal Block Cache Memory",
     "query": "state_store_block_cache_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 1.1"
    },
    {
     "expr": "state_store_uploading_memory_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 0.7",
     "legendFormat": "Abnormal Uploading Memory Usage",
     "query": "state_store_uploading_memory_usage_ratio{job=~\"$job\",instance=~\"$node\"} >= bool 0.7"
    },
    {
     "expr": "storage_write_stop_compaction_groups{job=~\"$job\",instance=~\"$node\"} > bool 0",
     "legendFormat": "Write Stall",
     "query": "storage_write_stop_compaction_groups{job=~\"$job\",instance=~\"$node\"} > bool 0"
    },
    {
     "expr": "storage_version_size{job=~\"$job\",instance=~\"$node\"} >= bool 314572800",
     "legendFormat": "Abnormal Version Size",
     "query": "storage_version_size{job=~\"$job\",instance=~\"$node\"} >= bool 314572800"
    },
    {
     "expr": "storage_delta_log_count{job=~\"$job\",instance=~\"$node\"} >= bool 5000",
     "legendFormat": "Abnormal Delta Log Number",
     "query": "storage_delta_log_count{job=~\"$job\",instance=~\"$node\"} >= bool 5000"
    },
    {
     "expr": "state_store_event_handler_pending_event{job=~\"$job\",instance=~\"$node\"} >= bool 10000000",
     "legendFormat": "Abnormal Pending Event Number",
     "query": "state_store_event_handler_pending_event{job=~\"$job\",instance=~\"$node\"} >= bool 10000000"
    },
    {
     "expr": "object_store_failure_count{job=~\"$job\",instance=~\"$node\"} >= bool 50",
     "legendFormat": "Abnormal Object Storage Failure",
     "query": "object_store_failure_count{job=~\"$job\",instance=~\"$node\"} >= bool 50"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors in the system group by type",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(user_compute_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, executor_name, fragment_id)",
     "legendFormat": "{{error_type}} @ {{executor_name}} (fragment_id={{fragment_id}})",
     "query": "sum(user_compute_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, executor_name, fragment_id)"
    },
    {
     "expr": "sum(user_source_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, source_id, source_name, fragment_id)",
     "legendFormat": "{{error_type}} @ {{source_name}} (source_id={{source_id}} fragment_id={{fragment_id}})",
     "query": "sum(user_source_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, source_id, source_name, fragment_id)"
    },
    {
     "expr": "sum(user_sink_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, sink_id, sink_name, fragment_id)",
     "legendFormat": "{{error_type}} @ {{sink_name}} (sink_id={{sink_id}} fragment_id={{fragment_id}})",
     "query": "sum(user_sink_error{job=~\"$job\",instance=~\"$node\"}) by (error_type, sink_id, sink_name, fragment_id)"
    },
    {
     "expr": "source_status_is_up{job=~\"$job\",instance=~\"$node\"} == 0",
     "legendFormat": "source error: source_id={{source_id}}, source_name={{source_name}} @ {{instance}}",
     "query": "source_status_is_up{job=~\"$job\",instance=~\"$node\"} == 0"
    },
    {
     "expr": "sum(rate(object_store_failure_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance, job, type)",
     "legendFormat": "remote storage error {{type}}: {{job}} @ {{instance}}",
     "query": "sum(rate(object_store_failure_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance, job, type)"
    }
   ]
  },
  {
   "title": "Batch Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Qps" } },
   "targets": [
    {
     "expr": "rate(frontend_query_counter_local_execution{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Local mode",
     "query": "rate(frontend_query_counter_local_execution{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])"
    },
    {
     "expr": "rate(distributed_completed_query_counter{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Distributed mode",
     "query": "rate(distributed_completed_query_counter{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "The number of each type of RisingWave components alive.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(worker_num{job=~\"$job\",instance=~\"$node\"}) by (worker_type)",
     "legendFormat": "{{worker_type}}",
     "query": "sum(worker_num{job=~\"$job\",instance=~\"$node\"}) by (worker_type)"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "description": "Number of active sessions in frontend nodes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "frontend_active_sessions{job=~\"$job\",instance=~\"$node\"}",
     "query": "frontend_active_sessions{job=~\"$job\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "description": "The CPU usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}",
       "query": "sum(rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Node CPU Core Number",
     "type": "timeseries",
     "description": "Number of CPU cores per RisingWave component.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "avg(process_cpu_core_num{job=~\"$job\",instance=~\"$node\"}) by (instance)",
       "legendFormat": "{{instance}}",
       "query": "avg(process_cpu_core_num{job=~\"$job\",instance=~\"$node\"}) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory",
     "type": "timeseries",
     "description": "The memory usage of each RisingWave component.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{job=~\"$job\",instance=~\"$node\"}) by (job,instance)",
       "legendFormat": "{{job}} @ {{instance}}",
       "query": "avg(process_resident_memory_bytes{job=~\"$job\",instance=~\"$node\"}) by (job,instance)"
      }
     ]
    },
    {
     "title": "Memory Usage (Total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(state_store_meta_cache_size{job=~\"$job\",instance=~\"$node\"}) by (instance) + sum(state_store_block_cache_size{job=~\"$job\",instance=~\"$node\"}) by (instance) + sum(uploading_memory_size{job=~\"$job\",instance=~\"$node\"}) by (instance)",
       "legendFormat": "storage @ {{instance}}",
       "query": "sum(state_store_meta_cache_size{job=~\"$job\",instance=~\"$node\"}) by (instance) + sum(state_store_block_cache_size{job=~\"$job\",instance=~\"$node\"}) by (instance) + sum(uploading_memory_size{job=~\"$job\",instance=~\"$node\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Memory Usage (Detailed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(state_store_meta_cache_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)",
       "legendFormat": "storage meta cache - {{job}} @ {{instance}}",
       "query": "sum(state_store_meta_cache_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)"
      },
      {
       "expr": "sum(state_store_block_cache_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)",
       "legendFormat": "storage block cache - {{job}} @ {{instance}}",
       "query": "sum(state_store_block_cache_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)"
      },
      {
       "expr": "sum(uploading_memory_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)",
       "legendFormat": "storage write buffer - {{job}} @ {{instance}}",
       "query": "sum(uploading_memory_size{job=~\"$job\",instance=~\"$node\"}) by (job,instance)"
      },
      {
       "expr": "sum(stream_memory_usage{job=~\"$job\",instance=~\"$node\"} * on(table_id) group_left(materialized_view_id) table_info) by (materialized_view_id)",
       "legendFormat": "materialized_view {{materialized_view_id}}",
       "query": "sum(stream_memory_usage{job=~\"$job\",instance=~\"$node\"} * on(table_id) group_left(materialized_view_id) table_info) by (materialized_view_id)"
      }
     ]
    },
    {
     "title": "Executor Cache Miss Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(stream_join_lookup_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (side, join_table_id, degree_table_id, fragment_id) ) / (sum(rate(stream_join_lookup_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (side, join_table_id, degree_table_id, fragment_id)) >= 0",
       "legendFormat": "Join executor cache miss ratio - - {{side}} side, join_table_id {{join_table_id}} degree_table_id {{degree_table_id}} fragment {{fragment_id}}",
       "query": "(sum(rate(stream_join_lookup_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (side, join_table_id, degree_table_id, fragment_id) ) / (sum(rate(stream_join_lookup_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (side, join_table_id, degree_table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_agg_lookup_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_lookup_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Agg cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_agg_lookup_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_lookup_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_agg_state_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_state_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Agg state cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_agg_state_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_state_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_agg_distinct_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_distinct_total_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Distinct agg cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_agg_distinct_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_agg_distinct_total_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_group_top_n_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_group_top_n_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Stream group top n cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_group_top_n_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_group_top_n_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_group_top_n_appendonly_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_group_top_n_appendonly_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Stream group top n appendonly cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_group_top_n_appendonly_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_group_top_n_appendonly_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_lookup_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_lookup_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Stream lookup cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_lookup_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_lookup_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_temporal_join_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_temporal_join_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Stream temporal join cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_temporal_join_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_temporal_join_total_query_cache_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "1 - (sum(rate(stream_materialize_cache_hit_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_materialize_cache_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Materialize executor cache miss ratio - table {{table_id}} fragment {{fragment_id}}",
       "query": "1 - (sum(rate(stream_materialize_cache_hit_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_materialize_cache_total_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_over_window_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Over window cache miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_over_window_cache_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_over_window_range_cache_left_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_range_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Over window partition range cache left miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_over_window_range_cache_left_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_range_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      },
      {
       "expr": "(sum(rate(stream_over_window_range_cache_right_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_range_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0",
       "legendFormat": "Over window partition range cache right miss ratio - table {{table_id}} fragment {{fragment_id}} ",
       "query": "(sum(rate(stream_over_window_range_cache_right_miss_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id) ) / (sum(rate(stream_over_window_range_cache_lookup_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (table_id, fragment_id)) >= 0"
      }
     ]
    },
    {
     "title": "Storage Cache",
     "type": "timeseries",
     "description": "Storage cache statistics",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(state_store_sst_store_block_request_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job, instance, table_id, type)",
       "legendFormat": "memory cache - {{table_id}} @ {{type}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_sst_store_block_request_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job, instance, table_id, type)"
      },
      {
       "expr": "sum(rate(state_store_sst_store_block_request_counts{type='meta_miss',job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job, type)",
       "legendFormat": "total_meta_miss_count - {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_sst_store_block_request_counts{type='meta_miss',job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job, type)"
      }
     ]
    },
    {
     "title": "Storage Bloom Filer",
     "type": "timeseries",
     "description": "Storage bloom filter statistics",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(state_store_read_req_check_bloom_filter_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter total - {{table_id}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_read_req_check_bloom_filter_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job,instance,table_id)"
      },
      {
       "expr": "sum(rate(state_store_read_req_positive_but_non_exist_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job,instance,table_id)",
       "legendFormat": "bloom filter false positive  - {{table_id}} @ {{job}} @ {{instance}}",
       "query": "sum(rate(state_store_read_req_positive_but_non_exist_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job,instance,table_id)"
      }
     ]
    },
    {
     "title": "Storage File Cache",
     "type": "timeseries",
     "description": "Storage file cache statistics",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_latency_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (op, instance)",
       "legendFormat": "file cache {{op}} @ {{instance}}",
       "query": "sum(rate(file_cache_latency_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (op, instance)"
      },
      {
       "expr": "sum(rate(file_cache_miss{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "file cache miss @ {{instance}}",
       "query": "sum(rate(file_cache_miss{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streaming Remote Exchange (Bytes/s)",
     "type": "timeseries",
     "description": "Send/Recv throughput per node for streaming exchange",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(stream_exchange_frag_send_size{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Send @ {{instance}}",
       "query": "sum(rate(stream_exchange_frag_send_size{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      },
      {
       "expr": "sum(rate(stream_exchange_frag_recv_size{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Recv @ {{instance}}",
       "query": "sum(rate(stream_exchange_frag_recv_size{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput per node",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "read - {{instance}}",
       "query": "sum(rate(object_store_read_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      },
      {
       "expr": "sum(rate(object_store_write_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "write - {{instance}}",
       "query": "sum(rate(object_store_write_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      }
     ]
    },
    {
     "title": "Batch Exchange Recv (Rows/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "sum(rate(batch_exchange_recv_row_number{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Recv @ {{instance}}",
       "query": "sum(rate(batch_exchange_recv_row_number{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Size",
     "type": "timeseries",
     "description": "\n                    Objects are classified into 3 groups:\n                    - not referenced by versions: these object are being deleted from object store.\n                    - referenced by non-current versions: these objects are stale (not in the latest version), but those old versions may still be in use (e.g. long-running pinning). Thus those objects cannot be deleted at the moment.\n                    - referenced by current version: these objects are in the latest version.\n                    ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_stale_object_size{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "not referenced by versions",
       "query": "storage_stale_object_size{job=~\"$job\",instance=~\"$node\"}"
      },
      {
       "expr": "storage_old_version_object_size{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "referenced by non-current versions",
       "query": "storage_old_version_object_size{job=~\"$job\",instance=~\"$node\"}"
      },
      {
       "expr": "storage_current_version_object_size{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "referenced by current version",
       "query": "storage_current_version_object_size{job=~\"$job\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Materialized View Size",
     "type": "timeseries",
     "description": "The storage size of each materialized view",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "storage_materialized_view_stats{metric='materialized_view_total_size',job=~\"$job\",instance=~\"$node\"}/1024",
       "legendFormat": "{{metric}}, mv id - {{table_id}} ",
       "query": "storage_materialized_view_stats{metric='materialized_view_total_size',job=~\"$job\",instance=~\"$node\"}/1024"
      }
     ]
    },
    {
     "title": "Object Total Number",
     "type": "timeseries",
     "description": "\n                    Objects are classified into 3 groups:\n                    - not referenced by versions: these object are being deleted from object store.\n                    - referenced by non-current versions: these objects are stale (not in the latest version), but those old versions may still be in use (e.g. long-running pinning). Thus those objects cannot be deleted at the moment.\n                    - referenced by current version: these objects are in the latest version.\n                    ",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "targets": [
      {
       "expr": "storage_stale_object_count{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "not referenced by versions",
       "query": "storage_stale_object_count{job=~\"$job\",instance=~\"$node\"}"
      },
      {
       "expr": "storage_old_version_object_count{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "referenced by non-current versions",
       "query": "storage_old_version_object_count{job=~\"$job\",instance=~\"$node\"}"
      },
      {
       "expr": "storage_current_version_object_count{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "referenced by current version",
       "query": "storage_current_version_object_count{job=~\"$job\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "timeseries",
     "description": "The number of bytes that have been written by compaction.Flush refers to the process of compacting Memtables to SSTables at Level 0.Compaction refers to the process of compacting SSTables at one level to another level.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_compact_write{job=~\"$job\",instance=~\"$node\"}) by (job) > 0",
       "legendFormat": "Compaction - {{job}}",
       "query": "sum(storage_level_compact_write{job=~\"$job\",instance=~\"$node\"}) by (job) > 0"
      },
      {
       "expr": "sum(compactor_write_build_l0_bytes{job=~\"$job\",instance=~\"$node\"}) by (job) > 0",
       "legendFormat": "Flush - {{job}}",
       "query": "sum(compactor_write_build_l0_bytes{job=~\"$job\",instance=~\"$node\"}) by (job) > 0"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (Bytes/s)",
     "type": "timeseries",
     "description": "The remote storage read/write throughput",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job)",
       "legendFormat": "read - {{job}}",
       "query": "sum(rate(object_store_read_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job)"
      },
      {
       "expr": "sum(rate(object_store_write_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job)",
       "legendFormat": "write - {{job}}",
       "query": "sum(rate(object_store_write_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (job)"
      }
     ]
    },
    {
     "title": "Checkpoint Size",
     "type": "timeseries",
     "description": "Size statistics for checkpoint",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job))",
       "legendFormat": "p50 - {{job}}",
       "query": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job))"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job))",
       "legendFormat": "p99 - {{job}}",
       "query": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job))"
      },
      {
       "expr": "sum by(le, job) (rate(state_store_sync_size_sum{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) / sum by(le, job) (rate(state_store_sync_size_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) > 0",
       "legendFormat": "avg - {{job}}",
       "query": "sum by(le, job) (rate(state_store_sync_size_sum{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) / sum by(le, job) (rate(state_store_sync_size_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Throughput (rows/s)",
     "type": "timeseries",
     "description": "The figure shows the number of rows read by each source per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "sum(rate(stream_source_output_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)",
       "legendFormat": "{{source_id}} {{source_name}} (fragment {{fragment_id}})",
       "query": "sum(rate(stream_source_output_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)"
      },
      {
       "expr": "sum(rate(file_source_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)",
       "legendFormat": "{{source_name}} source_id {{source_id}} (fragment {{fragment_id}})",
       "query": "sum(rate(file_source_input_row_count{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)"
      }
     ]
    },
    {
     "title": "Source Throughput (MB/s)",
     "type": "timeseries",
     "description": "The figure shows the number of bytes read by each source per second.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "MB/s" } },
     "targets": [
      {
       "expr": "(sum by (source_id)(rate(partition_input_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])))/(1000*1000)",
       "legendFormat": "source={{source_id}}",
       "query": "(sum by (source_id)(rate(partition_input_bytes{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])))/(1000*1000)"
      }
     ]
    },
    {
     "title": "Source Backfill Throughput (rows/s)",
     "type": "timeseries",
     "description": "The figure shows the number of rows read by each source per second.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "sum(rate(stream_source_backfill_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)",
       "legendFormat": "{{source_id}} {{source_name}} (fragment {{fragment_id}})",
       "query": "sum(rate(stream_source_backfill_rows_counts{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (source_id, source_name, fragment_id)"
      }
     ]
    },
    {
     "title": "Materialized View Throughput (rows/s)",
     "type": "timeseries",
     "description": "The figure shows the number of rows written into each materialized executor actor per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "sum(rate(stream_executor_row_count{executor_identity=~\".*MaterializeExecutor.*\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) * on(actor_id) group_left(materialized_view_id, table_name) (group(table_info{table_type=~\"MATERIALIZED_VIEW\",job=~\"$job\",instance=~\"$node\"}) by (actor_id, materialized_view_id, table_name))) by (materialized_view_id, table_name)",
       "legendFormat": "materialized view {{table_name}} table_id {{materialized_view_id}}",
       "query": "sum(rate(stream_executor_row_count{executor_identity=~\".*MaterializeExecutor.*\",job=~\"$job\",instance=~\"$node\"}[$__rate_interval]) * on(actor_id) group_left(materialized_view_id, table_name) (group(table_info{table_type=~\"MATERIALIZED_VIEW\",job=~\"$job\",instance=~\"$node\"}) by (actor_id, materialized_view_id, table_name))) by (materialized_view_id, table_name)"
      }
     ]
    },
    {
     "title": "Backfill Throughput (rows/s)",
     "type": "timeseries",
     "description": "Total number of rows that have been read from the backfill operator used by MV on MV",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "\n                                sum by (table_id) (\n                                  rate(stream_backfill_snapshot_read_row_count{table_id=~\"$table|\"}[$__rate_interval])\n                                )\n                                * on(table_id) group_left(table_name) (\n                                  group(table_info) by (table_name, table_id)\n                                )\n                            ",
       "legendFormat": "{{table_id}}: {{table_name}} snapshot-read",
       "query": "\n                                sum by (table_id) (\n                                  rate(stream_backfill_snapshot_read_row_count{table_id=~\"$table|\"}[$__rate_interval])\n                                )\n                                * on(table_id) group_left(table_name) (\n                                  group(table_info) by (table_name, table_id)\n                                )\n                            "
      },
      {
       "expr": "\n                                sum by (table_id) (\n                                  rate(stream_backfill_upstream_output_row_count{table_id=~\"$table|\"}[$__rate_interval])\n                                )\n                                * on(table_id) group_left(table_name) (\n                                  group(table_info) by (table_name, table_id)\n                                )\n                            ",
       "legendFormat": "{{table_id}}: {{table_name}} upstream",
       "query": "\n                                sum by (table_id) (\n                                  rate(stream_backfill_upstream_output_row_count{table_id=~\"$table|\"}[$__rate_interval])\n                                )\n                                * on(table_id) group_left(table_name) (\n                                  group(table_info) by (table_name, table_id)\n                                )\n                            "
      }
     ]
    },
    {
     "title": "Actor Output Blocking Time Ratio (Backpressure)",
     "type": "timeseries",
     "description": "We first record the total blocking duration(ns) of output buffer of each actor. It shows how much time it takes an actor to process a message, i.e. a barrier, a watermark or rows of data, on average. Then we divide this duration by 1 second and show it as a percentage.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(rate(stream_actor_output_buffer_blocking_duration_ns{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (fragment_id, downstream_fragment_id) / 1000000000",
       "legendFormat": "fragment {{fragment_id}}->{{downstream_fragment_id}}",
       "query": "avg(rate(stream_actor_output_buffer_blocking_duration_ns{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (fragment_id, downstream_fragment_id) / 1000000000"
      }
     ]
    },
    {
     "title": "Latency of Materialize Views & Sinks",
     "type": "timeseries",
     "description": "The current epoch that the Materialize Executors or Sink Executor are processing. If an MV/Sink's epoch is far behind the others, it's very likely to be the performance bottleneck",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(timestamp(stream_mview_current_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(stream_mview_current_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (table_id) * on(table_id) group_left(table_name) group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name)",
       "legendFormat": "{{table_id}} {{table_name}}",
       "query": "max(timestamp(stream_mview_current_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(stream_mview_current_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (table_id) * on(table_id) group_left(table_name) group(table_info{job=~\"$job\",instance=~\"$node\"}) by (table_id, table_name)"
      },
      {
       "expr": "max(timestamp(log_store_latest_read_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(log_store_latest_read_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (sink_id, sink_name)",
       "legendFormat": "{{sink_id}} {{sink_name}} (output)",
       "query": "max(timestamp(log_store_latest_read_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(log_store_latest_read_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (sink_id, sink_name)"
      },
      {
       "expr": "max(timestamp(log_store_latest_write_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(log_store_latest_write_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (sink_id, sink_name)",
       "legendFormat": "{{sink_id}} {{sink_name}} (enqueue)",
       "query": "max(timestamp(log_store_latest_write_epoch{job=~\"$job\",instance=~\"$node\"}) - (1617235200000+(log_store_latest_write_epoch{job=~\"$job\",instance=~\"$node\"} != 0)/65536)/1000) by (sink_id, sink_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "distributed_running_query_num{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "The number of running query in distributed execution mode",
       "query": "distributed_running_query_num{job=~\"$job\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Rejected query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "distributed_rejected_query_counter{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "The number of rejected query in distributed execution mode",
       "query": "distributed_rejected_query_counter{job=~\"$job\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Completed query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "targets": [
      {
       "expr": "distributed_completed_query_counter{job=~\"$job\",instance=~\"$node\"}",
       "legendFormat": "The number of completed query in distributed execution mode",
       "query": "distributed_completed_query_counter{job=~\"$job\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Query Latency in Distributed Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.99, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pmax - {{job}} @ {{instance}}",
       "query": "histogram_quantile(1.0, sum(rate(distributed_query_latency_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      }
     ]
    },
    {
     "title": "Query Latency in Local Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p50 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p90 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "p99 - {{job}} @ {{instance}}",
       "query": "histogram_quantile(0.99, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pmax - {{job}} @ {{instance}}",
       "query": "histogram_quantile(1.0, sum(rate(frontend_latency_local_execution_bucket{job=~\"$job\",instance=~\"$node\"}[$__rate_interval])) by (le, job, instance))"
      }
     ]
    }
   ]
  }
 ]
}