apiVersion: 1
deleteDatasources:
  - name: prometheus
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9500
    withCredentials: false
    isDefault: true
    tlsAuth: false
    tlsAuthWithCACert: false
    version: 1
    editable: true
